export const STATUS = {
  LANGUAGE_UPDATE: 'LANGUAGE_UPDATE',
  UPDATE_ERROR_DETAIL: 'UPDATE_ERROR_DETAIL',
  UPDATE_LOGIN_STATE: 'UPDATE_LOGIN_STATE',
  UPDATE_REGISTER_STATE: 'UPDATE_REGISTER_STATE'
}

export const ADMIN = {
  GET_ALL_COLLEGE_INFO: 'GET_ALL_COLLEGE_INFO',
  GET_ALL_COLLEGE_INFO_SAVE: 'GET_ALL_COLLEGE_INFO_SAVE',
  SCRAP_COLLEGE_DATA_ASYNC: 'SCRAP_COLLEGE_DATA_ASYNC',
  SCRAP_COLLEGE_RANKING_ASYNC: 'SCRAP_COLLEGE_RANKING_ASYNC',
  IMPORT_COLLEGE_SCORECARD_ASYNC: 'IMPORT_COLLEGE_SCORECARD_ASYNC',
  EXPORT_COLLEGE_INFO_ASYNC: 'EXPORT_COLLEGE_INFO_ASYNC',
  GET_ALL_PROFILE_INFO: 'GET_ALL_PROFILE_INFO',
  GET_ALL_PROFILE_INFO_SAVE: 'GET_ALL_PROFILE_INFO_SAVE',
  IMPORT_PROFILE_ASYNC: 'IMPORT_PROFILE_ASYNC',
  DELETE_ALL_PROFILES_ASYNC: 'DELETE_ALL_PROFILES_ASYNC',
  GET_APPLICATIONS_INFO: 'GET_APPLICATIONS_INFO',
  GET_APPLICATIONS_INFO_SAVE: 'GET_APPLICATIONS_INFO_SAVE',
  CHANGE_QUESTIONABLE_DECISION_ASYNC: 'CHANGE_QUESTIONABLE_DECISION_ASYNC'
}

export const USER = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
}

export const PROFILE = {
  EDIT_EDUCATION: 'EDIT_EDUCATION',
  EDIT_ACT_GRADE: 'EDIT_ACT_GRADE',
  EDIT_SAT_GRADE: 'EDIT_SAT_GRADE',
  EDIT_APPLICATION: 'EDIT_APPLICATION',
  UNEDIT_APPLICATION: 'UNEDIT_APPLICATION',
  GET_PROFILE: 'GET_PROFILE',
  SAVE_PROFILE: 'SAVE_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
}

export const APPLICATION = {
  GET_APPLICATION: 'GET_APPLICATION',
  SAVE_APPLICATION: 'SAVE_APPLICATION',
  DELETE_APPLICATION: 'DELETE_APPLICATION',
  UPDATE_APPLICATION: 'UPDATE_APPLICATION'
}

export const FINDHIGHSCHOOL = {
  SEARCH_SIMILAR_HIGHSCHOOLS: 'SEARCH_SIMILAR_HIGHSCHOOLS',
  SAVE_SIMILAR_HIGHSCHOOLS: 'SAVE_SIMILAR_HIGHSCHOOLS'
}