spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  application:
    name: c4me-server
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
      port: 8080
