spring:
  profiles:
    active: dev
  application:
    name: c4me-system
  boot:
    admin:
      client:
        url: http://localhost:8060
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka

server:
  port: 3001