spring:
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  application:
    name: c4me-server
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka

server:
      port: 3000